### ISSUE TITLE
fadeInDesktop/fadeOutDesktop removed in gnome-shell 42+

### ISSUE THREAD

**Issue by colingibbs1** [RensAlthuis/vertical-overview#103]
See gnome-shell commit here:
  https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/2127222b39c763d2f018ecd03e4d6abdc995d1b0

This causes `JS ERROR: TypeError: Main.overview.fadeInDesktop is not a function`

Along with the fixes from #101 this works with gnome-shell 42.0-2 in debian sid.

```
diff --git a/overviewControls.js b/overviewControls.js
index 77a2a67..19c5a46 100644
--- a/overviewControls.js
+++ b/overviewControls.js
@@ -337,8 +337,6 @@ var ControlsManagerOverride = {
 
         this._searchController.prepareToEnterOverview();
         this._workspacesDisplay.prepareToEnterOverview();
-        if (!this._workspacesDisplay.activeWorkspaceHasMaximizedWindows())
-            Main.overview.fadeOutDesktop();
 
         this._stateAdjustment.value = ControlsState.HIDDEN;
 
@@ -369,8 +367,6 @@ var ControlsManagerOverride = {
         this._ignoreShowAppsButtonToggle = true;
 
         this._workspacesDisplay.prepareToLeaveOverview();
-        if (!this._workspacesDisplay.activeWorkspaceHasMaximizedWindows())
-            Main.overview.fadeInDesktop();
 
         this._stateAdjustment.ease(ControlsState.HIDDEN, {
             duration: Overview.ANIMATION_TIME,
```

**Comment by wlayher** [comment]
Yes, thank you. This works for me as well on debian sid.

**Comment by jfernandz** [comment]
The patch also works for `gnome-shell 1:42.1-1` in Arch Linux. But sure, it must be applied over `564dc75` :wink: thank you @colingibbs1
